#!/usr/bin/env python3
"""post_tool_use Hook 入口"""
import os
import sys

HOOK_ROOT = os.environ.get("HOOK_ROOT", "/brain/base/hooks")
os.environ["HOOK_ROOT"] = HOOK_ROOT

sys.path.insert(0, os.path.join(HOOK_ROOT, "tool_validation"))
sys.path.insert(0, os.path.join(HOOK_ROOT, "session"))
sys.path.insert(0, os.path.join(HOOK_ROOT, "checkers", "audit_logger"))
sys.path.insert(0, os.path.join(HOOK_ROOT, "utils"))
sys.path.insert(0, os.path.join(HOOK_ROOT, "lep"))

from tool_validation.handler import handle_post_tool_use

if __name__ == "__main__":
    handle_post_tool_use()
