#!/usr/bin/env python3
"""user_prompt_submit Hook 入口"""
import os
import sys

HOOK_ROOT = os.environ.get("HOOK_ROOT", "/brain/base/hooks")
os.environ["HOOK_ROOT"] = HOOK_ROOT

sys.path.insert(0, os.path.join(HOOK_ROOT, "tool_validation"))
sys.path.insert(0, os.path.join(HOOK_ROOT, "session"))
sys.path.insert(0, os.path.join(HOOK_ROOT, "checkers", "audit_logger"))
sys.path.insert(0, os.path.join(HOOK_ROOT, "utils"))
sys.path.insert(0, os.path.join(HOOK_ROOT, "lep"))

from session.handler import handle_user_prompt_submit

if __name__ == "__main__":
    handle_user_prompt_submit()
