name: brain_timer
description: Brain Infrastructure Service
version: 1.0.0
type: service
language: python

paths:
  project_root: /xkagent_infra/groups/brain/projects/infrastructure/brain_timer
  infra_service: /xkagent_infra/brain/infrastructure/service/brain_timer

dependencies: []

build:
  type: python

deploy:
  method: copy
