[program:service_litellm_proxy]
command=/brain/infrastructure/service/litellm_proxy/releases/current/bin/start
directory=/brain/infrastructure/service/litellm_proxy
user=root
autostart=false
autorestart=true
startsecs=10
stopwaitsecs=10
stdout_logfile=/xkagent_infra/runtime/logs/service_litellm_proxy.stdout.log
stderr_logfile=/xkagent_infra/runtime/logs/service_litellm_proxy.stderr.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=5
environment=
  DAEMON_SOCKET=/tmp/brain_ipc.sock,
  SERVICE_NAME=service-litellm_proxy,
  KIMI_API_KEY=sk-kimi-EUDSyOFT31PINddOl7pcv3YPBMHDJa7v78Gw4NgZK2hh5pfpefZSHftckQqpLxBL,
  OPENAI_API_KEY=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,
  MINIMAX_API_KEY=sk-cp-K4C4JjIKInImKH9GlH8bjxEfqlItpqYVyH0YOzjgl6KRLpOqKUa2HKc0LUVm1I059-un9lPzijrVgEhA7sTRjVfh-2u9Yu4T6nWGa6P4_jEaY-9t7SVFZw,
  BYTEDANCE_API_KEY=25b692f8-57d8-49e1-858d-457e2db627f4,
  QWEN_API_KEY=sk-sp-abcf083e1f0843fc8098bd0be53e118e
