[program:service_litellm_proxy]
command=/brain/infrastructure/service/litellm_proxy/releases/current/bin/start
directory=/brain/infrastructure/service/litellm_proxy
user=root
autostart=false
autorestart=true
startsecs=10
stopwaitsecs=10
stdout_logfile=/xkagent_infra/runtime/logs/service_litellm_proxy.stdout.log
stderr_logfile=/xkagent_infra/runtime/logs/service_litellm_proxy.stderr.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=5
environment=
  DAEMON_SOCKET=/tmp/brain_ipc.sock,
  SERVICE_NAME=service-litellm_proxy
