[program:service_llm_quota]
command=/brain/infrastructure/service/llm_quota_manager/start.sh
directory=/brain/infrastructure/service/llm_quota_manager
user=root
autostart=false
autorestart=true
startsecs=10
stopwaitsecs=10
stdout_logfile=/brain/runtime/logs/service_llm_quota.stdout.log
stderr_logfile=/brain/runtime/logs/service_llm_quota.stderr.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=5
environment=
  DAEMON_SOCKET=/tmp/brain_ipc.sock,
  SERVICE_NAME=service-llm_quota
