version: "2.1.0"
date: "2026-02-27"
timestamp: "2026-02-27T12:13:21Z"
published_by: build.sh
git_commit: "91ae885f"
domains:
  spec:      true
  workflow:  true
  knowledge: true
  evolution: true
  skill:     true
  index:     true
