version: '1.0'
clients:
  bgw-client-v1-c0ca182810dda8a1b77e7bdfa5b486d2:
    agent_name: agent-brain_manager
    description: Brain manager (resident)
    provider: minimax
    model: minimax-m2.7
  bgw-client-v1-fee4665eb5f723a9a80dd97cbbb3ad27:
    agent_name: agent-brain_frontdesk
    description: Brain 前台接待 Agent
    provider: copilot
    model: gpt-5-mini
  bgw-client-v1-e241c550d39723dd03248d405ce157d5:
    agent_name: agent-brain_devops
    description: brain 的 devops Agent
    provider: minimax
    model: minimax-m2.7
  bgw-client-v1-f7be31cba1b6db9b2b6294dc97104f0d:
    agent_name: agent-brain_pmo
    description: brain 的 pmo Agent
    provider: minimax
    model: minimax-m2.7
  bgw-client-v1-0b2b9ff0b76636e0c2f1dc0b8d4bcd19:
    agent_name: agent_brain_dash-001_host_auditor
    description: brain 的 auditor Agent
    provider: minimax
    model: minimax-m2.7
  bgw-client-v1-31cd293603b0457d81dcf3cba1249e5e:
    agent_name: agent-brain_workflow_monitor
    description: brain 的 monitor Agent
    provider: claude
    model: claude-sonnet-4.6
  bgw-client-v1-fa757da0b72a80a15f328027fd088bfe:
    agent_name: agent-brain_nginx_config
    description: brain 的 config Agent
    provider: claude
    model: claude-sonnet-4.6
model_routing: {}
default_strategy: capability_match
model_strategy_map: {}
